### PR TITLE
Support CocoaPods

### PR DESCRIPTION
**Pull request by pepibumur**
**Issue:** [Link](https://github.com/carambalabs/xcodeproj/issues/34)

### Short description
Support CocoaPods

### Solution
I flatted the project hierarchy and included a `.podspec` with the specification of the library.

### Implementation
- [x] Flat the library folders hierarchy.
- [x] Include a `.podspec` file in the repository
- [x] Update the RELEASE process.
- [x] Release a new version of xcodeproj.

### GIF
gif

### CODE REVIEW

**Comment by pepibumur** [comment]
This PR is blocked by https://github.com/carambalabs/xcodeproj/pull/32 because we need to get rid of the CommonCrypto dependency.

**Comment by yonaskolb** [comment]
This is now unblocked

**Comment by pepibumur** [comment]
Yeah, I'll finish this one tomorrow. 😛

**Comment by pepibumur** [comment]
[CocoaPods support](https://trello.com/c/mdZuy3SK/14-cocoapods-support)

**Pull request merged**
