### PR TITLE
Migrate project to Swift 4

### PR DESCRIPTION
**Pull request by pepibumur**
**Issue:** [Link](https://github.com/carambalabs/xcodeproj/issues/13)

### Short description
Migrate the project to Swift 4

### Implementation
- [x] Update `Package.swift` syntax.
- [x] Bump `.swift-version` version.
- [x] Remove `Unbox` dependency.
- [ ] Refactor code to use the `Codable` protocol

### GIF
gif

### References
- [Codable protocol](https://developer.apple.com/documentation/swift/codable)

### CODE REVIEW

**Comment by yonaskolb** [comment]
Will this be merged in before #10? I was hoping to use this in a Swift 3 project after that was completed.
Don't let that stop you from your plans though :)

**Comment by yonaskolb** [comment]
Hi @pepibumur, just adding a mention here in case you didn't get a notification 👍

**Comment by pepibumur** [comment]
Hey @yonaskolb.
I'll prioritize the unique identifiers stuff so that you can use it from Swift 3. After that I'll migrate it to Swift 4. How does that sound?
By the way, how do you plan to use it. I'd love to hear how developers use the tool.

**Comment by yonaskolb** [comment]
Hi @pepibumur, sounds great! 😄 
I was planning to write a command line tool to generate an xcode project from a YAML file. I was looking for a good xcodeproject library in Swift before writing my own.
It seems you actually have the same aim in Cartago and Nova, is that right?

Is this repo at a point where an xcode project can be programatically created and then fully generated?

**Comment by pepibumur** [comment]
@yonaskolb that was my plan with [Cartago](https://github.com/carambalabs/cartago). The only missing part of the project is the generation of unique identifiers for objects, everything else can already be done. If you are interested we can collaborate on building up Cartago. My motivation was being able to automate the generation of projects. Although this is something you can sort of do with Xcode tempaltes, it's quite limiting.

**Comment by pepibumur** [comment]
We could extract all the repos together into its own GitHub organization.

**Comment by pepibumur** [comment]
I'll close this one until Swift 4 gets officially announced. We can come up with a transition plan by then :)

**Pull request closed without merging**
